
# This software is in public domain. It is intended to be customized by
# its nature. This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Please report bugs in VimDoxSpell to Vytautas.Shaltenis@gmail.com.
#
# VimDoxSpell's home page is at
# <http://rtfb.gamedev.lt/projects/vim-dox-spell/>.
#
# MAINTAINER: Vytautas Saltenis <Vytautas.Shaltenis@gmail.com>
#
# Copyright (C) 2008, Vytautas Saltenis

import os
import sys
import xml.dom.minidom

# These two variables are the things that this program asks the user
# to specify. It should be converted into arguments in a read program,
# but for the purpose of this example-ish program, it will do its job.
myTagsFile = '/home/rtfb/projects/vim-dox/tags-sample'
myIndexXml = '/home/rtfb/projects/vim-dox/index-sample.xml'

def getWordListFromTags (tagsFile):
    """Parses tags file, taking all the identifiers and stashing them
    into a list.
    """

    tags = open (tagsFile).readlines ()
    tags = filter (lambda l: not l.startswith ('!'), tags)
    words = []

    for t in tags:
        items = t.split ('\t')
        word = items[0]
        file = items[1]
        base, ext = os.path.splitext (file)

        # Add more extensions to this list, if you have other valid files
        if ext[1:].lower () in ['c', 'cpp', 'cc', 'cxx', 'h', 'fdf']:
            words.append (word)

    return words

def writeWordList (list, file):
    """Writes a given list of words to a given file. One word per line.
    """

    f = open (file, 'w')

    for w in list:
        f.write (w + '\n')

def getText (nodelist):
    """Retrieves a text between XML tags.
    """

    rc = ''

    for node in nodelist:
        if node.nodeType == node.TEXT_NODE:
            rc = rc + node.data

    return rc

def parseDoxygenIndex (file):
    """Parses the index file generated by doxygen. The information that
    is of interest there, are the names of the function groups, so that
    they can also be added to the dictionary of known words. Returned
    in a list.
    """

    contents = open (file).read ()
    dom = xml.dom.minidom.parseString (contents)
    compounds = dom.getElementsByTagName ('compound')
    groupNames = []

    for c in compounds:
        if c.attributes['kind'].nodeValue == 'group':
            group = getText (c.getElementsByTagName ('name')[0].childNodes)
            groupNames.append (group)

    return groupNames

def writeEmptySplFile (homeDir):
    """This one is tricky, if you don't know how Vim deals with its
    spelling dictionaries. For a proper explanation, refer to Vim
    documentation, and here it is sufficient to say, that I need a
    file 'fromtags.utf-8.spl', that is an empty dictionary. Vim will
    then not complain about being unable to find a dictionary. And all
    the real dictionary will be handled through another file,
    'fromtags.utf-8.add.spl', which is generated by this program.
    """

    emptySplFile = 'VIMspell2\xff' + '\x00' * 13
    emptySplFilePath = homeDir + '/.vim/spell/fromtags.utf-8.spl'
    open (emptySplFilePath, 'wb').write (emptySplFile)

def readThings (homeDir):
    """Reads tags and XML files to gather all the information needed
    to put into our dictionary of identifiers.
    """

    wordList = getWordListFromTags (myTagsFile)
    print 'tags read.'
    groupList = parseDoxygenIndex (myIndexXml)
    print 'doxygen index read.'
    return wordList + groupList

def writeThings (homeDir, things):
    """Writes the plain text list of identifiers and then calls Vim
    to generate an actual dictionary for its use.
    """

    dictFile = homeDir + '/.vim/spell/fromtags.utf-8.add'
    writeWordList (things, dictFile)
    print 'word list written.'

    writeEmptySplFile (homeDir)

    # The following command line calls Vim to generate the binary
    # dictionary file it will actually be using, not the plain text
    # one we've just written with writeWordList.
    cmd = 'vim -cmd ' + '":mkspell! %s"' % (dictFile) + ' --cmd ":q"'
    os.system (cmd)
    print 'spl generated.'

def main ():
    homeDir = os.environ['HOME']
    things = readThings (homeDir)
    writeThings (homeDir, things)
    print 'Done.'

if __name__ == '__main__':
    main ()

